pipeline {
   agent { label 'ec2-fleet'}

   stages {
      stage('Run Docker') {
         steps {
            sh 'docker info'
         }
      }

     stage('pwd') {
         steps {
             sh 'pwd'
          }
      }


      stage('Build number') {

         steps {
         echo "Build number is ${currentBuild.number}"
         }
      }


   }
}
