pipeline {
   agent { label 'java-docker-slave'}

   stages {
      stage('Hello') {
         steps {
            echo 'Hello World'
         }
      }

     stage('pwd') {
         steps {
             sh 'pwd'
          }
      }

      stage('check volume') {
         steps {
             sh 'cd /home/jenkins/mvn-repo'
             sh 'ls'
         }

      }


      stage('mvn test') {
         steps {
            sh 'mvn clean test'
          }
      }


   }
}
