pipeline {
   agent { label 'java-docker-slave'}

   stages {
      stage('Hello') {
         steps {
            echo 'Hello World'
         }
      }

     stage('pwd') {
         steps {
             sh 'pwd'
          }
      }

      stage('docker run') {
         steps {
             sh 'docker inspect gifted_galileo'
         }

      }


      stage('mvn test') {
         steps {
            sh 'mvn clean test'
          }
      }


   }
}
